export const API_URLS = {
  coinStore: {
    getCurrentOrders: '/api/trade/order/active',
    getCurrentOrdersV2: '/api/v2/trade/order/active',
    getLatestTrade: '/api/trade/match/accountMatches',
    cancelOrder: '/api/trade/order/cancel',
    oneClickCancellation: '/api/trade/order/cancelAll',
    createOrder: '/api/trade/order/place',
    batchOrdering: '/api/trade/order/placeBatch',
    batchCancellation: '/apitrade/order/cancelBatch',
    getOrderInfo: '/apitrade/order/orderInfo',
    getOrderInfoV2: '/api/v2/trade/order/orderInfo',
    getAssetsBalance: '/api/spot/accountList',
    getDepositAddress: '/api/fi/v3/asset/deposit/do',
    getDepositHistory: '/api/fi/v3/asset/deposit/record/list',
    getWithdrawalHistory: '/api/fi/v3/asset/withdraw/record/list',
    doWithdraw: '/api/fi/v3/asset/doWithdraw',
    cancelWithdraw: '/api/fi/v3/asset/cancelWithdraw',
    transferFund: '/api/v1/future/transfer',
    getSymbols: '/api/v2/public/config/spot/symbols',
    getCurrencyInfo: '/api/fi/v1/common/currency',
    getTickers: '/api/v1/market/tickers',
    getDepth: '/api/v1/market/depth',
    getKLine: '/api/v1/market/kline',
    getMarketLatestTrade: '/api/v1/market/trade',
    getLatestPrices: '/api/v1/ticker/price',
  },
  bybit: {
    // market
    getServerTime: '/v5/market/time',
    getKLine: '/v5/market/kline',
    getMarketPriceKLine: '/v5/market/mark-price-kline',
    getIndexPriceKLine: '/v5/market/index-price-kline',
    getPremiumIndexPriceKLine: '/v5/market/premium-index-price-kline',
    getInstrumentsInfo: '/v5/market/instruments-info',
    getOrderbook: '/v5/market/orderbook',
    getTickers: '/v5/market/tickers',
    getFundingRateHistory: '/v5/market/funding/history',
    getPublicRecentTradingHistory: '/v5/market/recent-trade',
    getOpenInterest: '/v5/market/open-interest',
    getHistoricalVolatility: '/v5/market/historical-volatility',
    getInsurance: '/v5/market/insurance',
    getRiskLimit: '/v5/market/risk-limit',
    getDeliveryPrice: '/v5/market/delivery-price',
    getLongShortRatio: '/v5/market/account-ratio',
    // trade
    placeOrder: '/v5/order/create',
    amendOrder: '/v5/order/amend',
    cancelOrder: '/v5/order/cancel',
    getRealTimeOpenAndClosedOrders: '/v5/order/realtime',
    cancelAllOrders: '/v5/order/cancel-all',
    getOrderHistory: '/v5/order/history',
    getTradeHistory: '/v5/execution/list',
    batchPlaceOrder: '/v5/order/create-batch',
    batchAmendOrder: '/v5/order/amend-batch',
    batchCancelOrder: '/v5/order/cancel-batch',
    getSpotBorrowQuota: '/v5/order/spot-borrow-check',
    setDCP: '/v5/order/disconnected-cancel-all',
  },
};

export const PAGINATION = {
  defaultRecords: 20,
};
